{{- if and (not .Values.marketingSsl.existingSecret) .Values.marketingSsl.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sommerfest-quiz.fullname" . }}-marketing-ssl
type: Opaque
stringData:
  MARKETING_SSL_API_TOKEN: {{ .Values.marketingSsl.apiToken | quote }}
  {{- if .Values.marketingSsl.apiUrl }}
  MARKETING_SSL_API_URL: {{ .Values.marketingSsl.apiUrl | quote }}
  {{- end }}
  {{- if .Values.marketingSsl.contactEmail }}
  MARKETING_SSL_CONTACT_EMAIL: {{ .Values.marketingSsl.contactEmail | quote }}
  {{- end }}
{{- end }}
