http:
  middlewares:
    quizrace-https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    quizrace-security-headers:
      headers:
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer-when-downgrade"
        customResponseHeaders:
          X-Frame-Options: "DENY"
          X-XSS-Protection: "1; mode=block"
    quizrace-body-limit-5m:
      buffering:
        maxRequestBodyBytes: 5242880
        memRequestBodyBytes: 2097152
        retryExpression: IsNetworkError()
    quizrace-body-limit-10m:
      buffering:
        maxRequestBodyBytes: 10485760
        memRequestBodyBytes: 2097152
        retryExpression: IsNetworkError()
    quizrace-body-limit-50m:
      buffering:
        maxRequestBodyBytes: 52428800
        memRequestBodyBytes: 2097152
        retryExpression: IsNetworkError()
